# Generated by Django 3.0.6 on 2020-05-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=16)),
                ('zip_code', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('social_security', models.CharField(max_length=26)),
                ('hire_date', models.DateField()),
                ('birth_date', models.DateField()),
                ('hourly_rate', models.FloatField()),
                ('title', models.CharField(max_length=26)),
                ('status', models.CharField(max_length=26)),
                ('gender', models.CharField(max_length=26)),
                ('worked_before', models.BooleanField()),
            ],
        ),
    ]
