# Generated by Django 3.0.6 on 2020-05-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_model',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='social_security',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='title',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='worked_before',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='zip_code',
        ),
    ]
