# Generated by Django 3.0.6 on 2020-05-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForm', '0002_auto_20200520_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='gender',
            field=models.CharField(default='male', max_length=26),
        ),
    ]
