# Generated by Django 3.0.6 on 2020-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForm', '0004_auto_20200520_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
