# Generated by Django 3.0.6 on 2020-05-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForm', '0005_employee_model_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_model',
            name='password',
        ),
    ]
