# Generated by Django 3.0.6 on 2020-05-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForm', '0006_remove_employee_model_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_model',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='employee_model',
            name='worked_before',
        ),
    ]
