# Generated by Django 3.0.6 on 2020-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForm', '0007_auto_20200520_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_model',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='city',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='name',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='social_security',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='state',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='status',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='title',
            field=models.CharField(max_length=26),
        ),
    ]
