# Generated by Django 3.0.6 on 2020-05-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForm', '0009_auto_20200520_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='address',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
