# Generated by Django 3.0.6 on 2020-05-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForm', '0011_employee_model_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='state',
            field=models.CharField(default='empty', max_length=16),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='zip_code',
            field=models.IntegerField(default='92'),
        ),
    ]
