# Generated by Django 3.0.6 on 2020-05-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForm', '0013_auto_20200520_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_model',
            name='password',
        ),
    ]
