# Generated by Django 3.0.6 on 2020-05-20 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeForm', '0016_employee_model_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='gender',
            field=models.CharField(default='male', max_length=26),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='hire_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='hourly_rate',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='status',
            field=models.CharField(default='empty', max_length=26),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='title',
            field=models.CharField(default='empty', max_length=26),
        ),
        migrations.AddField(
            model_name='employee_model',
            name='worked_before',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='name',
            field=models.CharField(default='empty', max_length=26),
        ),
        migrations.AlterField(
            model_name='employee_model',
            name='password',
            field=models.CharField(default='flkjsaf', max_length=50),
        ),
    ]
